//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dormitory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DormitoryDatabaseEntities3 : DbContext
    {
        public DormitoryDatabaseEntities3()
            : base("name=DormitoryDatabaseEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Block> Blocks { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Dorm> Dorms { get; set; }
        public virtual DbSet<DormPhone> DormPhones { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeLEtime> EmployeeLEtimes { get; set; }
        public virtual DbSet<Floor> Floors { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<Major> Majors { get; set; }
        public virtual DbSet<Monitor> Monitors { get; set; }
        public virtual DbSet<PublicPlace> PublicPlaces { get; set; }
        public virtual DbSet<ReportCondition> ReportConditions { get; set; }
        public virtual DbSet<RequestRoom> RequestRooms { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentLEtime> StudentLEtimes { get; set; }
        public virtual DbSet<Stuff> Stuffs { get; set; }
        public virtual DbSet<Uni> Unis { get; set; }
        public virtual DbSet<UniPhone> UniPhones { get; set; }
        public virtual DbSet<UserPhone> UserPhones { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
