//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dormitory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportCondition
    {
        public int ReportId { get; set; }
        public int StudentNum { get; set; }
        public int SId { get; set; }
        public string Condition { get; set; }
        public System.DateTime ReportCDate { get; set; }
        public string ConditionStatus { get; set; }
    
        public virtual Stuff Stuff { get; set; }
        public virtual Student Student { get; set; }
    }
}
