//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dormitory
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestRoom
    {
        public int RequestNum { get; set; }
        public int StudentNum { get; set; }
        public int RoomNum { get; set; }
        public int BlockNum { get; set; }
        public int FloorNum { get; set; }
        public System.DateTime Date { get; set; }
        public string RRType { get; set; }
        public string RRStatus { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Room Room { get; set; }
    }
}
