//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dormitory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Monitors = new HashSet<Monitor>();
            this.ReportConditions = new HashSet<ReportCondition>();
            this.RequestRooms = new HashSet<RequestRoom>();
            this.StudentLEtimes = new HashSet<StudentLEtime>();
        }
    
        public int StudentNum { get; set; }
        public bool Paid { get; set; }
        public int EnteranceYear { get; set; }
        public Nullable<int> RoomNum { get; set; }
        public int CityCode { get; set; }
        public int MId { get; set; }
        public int LId { get; set; }
        public Nullable<int> FloorNum { get; set; }
        public Nullable<int> BlockNum { get; set; }
        public int Mellicode { get; set; }
        public string DNType { get; set; }
    
        public virtual City City { get; set; }
        public virtual Level Level { get; set; }
        public virtual Major Major { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Monitor> Monitors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportCondition> ReportConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestRoom> RequestRooms { get; set; }
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentLEtime> StudentLEtimes { get; set; }
    }
}
